modkey = "Mod1"
mousekey = "Mod1"
workspaces = []
tags = ["1", "2", "3", "4", "5"]
layouts = ["MainAndVertStack", "MainAndDeck", "GridHorizontal", "LeftMain", "Monocle", "LeftWiderRightStack"]
layout_mode = "Workspace"
insert_behavior = "Bottom"
scratchpad = []
window_rules = [
	{ window_class = "Volume", spawn_floating = true }
]
disable_current_tag_swap = false
disable_tile_drag = false
disable_window_snap = true
focus_behaviour = "Sloppy"
focus_new_windows = true
max_window_width = 0.80

[[keybind]]
command = "Execute"
value = "/home/matt/Code/xmenu/xmenu.sh"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "st"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Control"]
key = "q"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "FloatingToTile"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["Mod4"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["Mod4"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["Mod4"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["Mod4"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["Mod4"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["Mod4", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["Mod4", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["Mod4", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["Mod4", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["Mod4", "Shift"]
key = "5"

[[keybind]]
command = "IncreaseMainWidth"
value = "2"
modifier = ["modkey", "Shift"]
key = "l"

[[keybind]]
command = "DecreaseMainWidth"
value = "2"
modifier = ["modkey", "Shift"]
key = "h"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"